name: Build APP
on: 
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: my-app
        steps:                    
            - name: descargar codigo  
              uses: actions/checkout@v4
                              
            - name: instalar node
              uses: actions/setup-node@v4
            
            - name: instalar dep       
              run: npm ci

            - name: ejecutar test              
              run: npm test
