name: Build APP
on: 
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: my-app 
        steps:                    
            - name: descargar codigo  
              uses: actions/checkout@v4
                              
            - name: instalar node
              uses: actions/setup-node@v4
            
            - name: Install Packages
              run: npm install
            
            - name: Build page
              run: npm run build

            - name: Build page 2
              run: tree -d .
              
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./my-app/build
