name: Build APP
on: 
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:                    
            - name: descargar codigo  
              uses: actions/checkout@v4              
                              
            - name: instalar node
              uses: actions/setup-node@v4
            
            - name: Install Packages
              run: npm install
              working-directory: my-app 
            
            - name: Build page
              run: npm run build
              working-directory: my-app 
            
            - name: Build page 2
              run: pwd

            - name: Build page 2
              run: ls -l
              
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./my-app/build
