name: Build APP
on: 
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:                    
            - name: descargar codigo  
              uses: actions/checkout@v4
                  
            - name: Ir al directorio
              run: cd my-app
            
            - name: instalar node
              uses: actions/setup-node@v4
            
            - name: pwd            
              run: pwd

            - name: instalar dep
              working-directory: my-app
              run: npm ci

            - name: ejecutar test
              working-directory: my-app
              run: npm test
