name: Build APP
on: 
    push: 

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:                    
            - name: descargar codigo  
              uses: actions/checkout@v4              
                              
            - name: instalar node
              uses: actions/setup-node@v4
            
            - name: Install Packages
              run: npm install
              working-directory: my-app 
            
            - name: Build page
              run: npm run build
              working-directory: my-app 
