name: Build APP
on: 
    woworkflow_dispatch:
        

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:                    
            - name: descargar codigo  
              uses: actions/checkout@v4              
                              
            - name: instalar node
              uses: actions/setup-node@v4

            - name: Cache Deps
              id: cache
              uses: actions/cache@v4
              with:
                path: my-app/node_modules
                key: my-app-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  my-app$-{{ hashFiles('**/package-lock.json') }}
                  my-app-                  
            
            - name: Install Packages
              if: ${{steps.cache.outputs.cache-hit != 'true'}}
              run: npm install
              working-directory: my-app 
            
            - name: Build page
              run: npm run build
              working-directory: my-app 


            - uses: actions/upload-artifact@v4
              with:
                name: my-app
                path: my-app/build
