name: Eventos

on:    
   push: 
      branches: 
         - main
         - develop   


jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "hola mundo, fui lanzado por el evento ${{github.event_name}}"