name: My JS Action

on:    
 workflow_dispatch:
jobs:
  job1:     
    runs-on: ubuntu-latest    
    steps:
      - name: Step1
        run: echo "Variable de org - ${{vars.ORG_VAR}}"
      - name: Use My custom JS Action
        uses: mad81github/myJSghAction@main