name: Eventos

on:    


   pull_request: 
    branches: 
         - main
         - develop 
    types: 
      - opened


jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "hola mundo, fui lanzado por el evento ${{github.event_name}} ${{github.ref_name}} - main"